version: "3.2"

volumes:
  mysql_data: {}

services:
  celery:
    build:
      context: .
      dockerfile: ./dockers/app/Dockerfile
    env_file:
      - ./.envs/.main_envs
    depends_on:
      - redis
    volumes:
      - ./src:/main
    restart: unless-stopped
    # command: sh /run_celery.sh
    command: sleep infinity
  flower:
    container_name: flower
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - FLOWER_PORT=8888
    depends_on:
      - redis
      - celery
    ports:
      - "8888:8888"
  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ./cache/redis:/data
  mysql:
    image: mysql:8.0
    expose:
      - "3306"
      - "33060"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "maindb"
      MYSQL_USER: "mainuser"
      MYSQL_PASSWORD: "mainpass"
    restart: unless-stopped
  grafana:
    image: grafana/grafana:7.1.4
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
  superset:
    image: amancevice/superset:0.18.5
    container_name: superset
    ports:
      - 8088:8088
